### PR TITLE
Class-based layout

### PR DESCRIPTION
**Pull request by ssorallen**
- `[vertical][reverse]` and `[horizontal][reverse]` become
  `.vertical-reverse` and `.horizontal-reverse`, respectively, to match
  `[wrap-reverse]`/`.wrap-reverse`
- `[flex][one]`, et al become `.flex-1`, `.flex-2`, etc. to shorten and
  move away from generic attributes/classes like "one" and "two"

Example:

``` html
<div layout horizontal reverse>
  <div flex one self-end></div>
  <div flex four></div>
</div>
```

becomes

``` html
<div class="layout horizontal-reverse">
  <div class="flex-1 self-end"></div>
  <div class="flex-4"></div>
</div>
```

### CODE REVIEW

**Comment by cdata** [comment]
Reading the HTML, I kind of like `one` better than `-1`. From a tools perspective, `-1` is probably easier to deal with.

I like it.

**Comment by ssorallen** [comment]
I considered converting "justified" (past tense) in the selectors to "justify" to match the CSS attributes too.

**Comment by SerkanSipahi** [comment]
@ssorallen : we opened here a Ticket about flexbox based layout ! You should continue the discussion here : https://github.com/Polymer/layout/issues/4 ,thanks.

**Comment by robdodson** [comment]
@ssorallen is there a reason to move away from the attributes (aside from the slowness of the CSS engine)?

**Comment by ssorallen** [comment]
@robdodson, there are a few reasons:
- Classes are the most common way of targeting selectors for CSS across other libraries, tutorials, and websites. For a dev or designer familiar with CSS, they will likely have used classes heavily in the past or have looked at Bootstrap, Foundation, the W3 Schools CSS tutorial, etc.
- Switching to attributes doesn't shorten or otherwise simplify selectors. There's no objective byte or specificity advantage over using classes (attributes actually add one character because of the closing bracket, but that's nitpicking).
  
  ``` css
  /* Both have specificity 0 1 0 */
  .flex { flex: 1; }
  [flex] { flex: 1; }
  
  /* Both have specificity 0 2 0 */
  .layout.horizontal { ... }
  [layout][horizontal] { ... }
  ```
- Custom attributes (like `layout`, `horizontal`, etc.) are invalid HTML for native HTML elements. Custom attributes on native elements must be prefixed with `data-` in the HTML5 spec.
  
  **Markup:**
  
  ``` html
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <title>Custom Attribute Test</title>
  </head>
  <body>
    <div layout horizontal>
      <div flex three></div>
      <div flex five></div>
    </div>
  </body>
  </html>
  ```
  
  **[HTML validator](http://validator.w3.org/#validate_by_input) output:**
  
  screen shot 2015-02-18 at 10 00 32 am

**Comment by robdodson** [comment]
@ssorallen yeah the last one is a valid point. I think the team must have been aware of that when they created the attributes but decided to go ahead with em anyway. I'd also add that you can use something like `tokenList` to flip them on and off if they're classes (at least in 0.5 world).

Having said that, the layout attributes are really nice! It's hard to explain why, but I really like using them as attributes instead of classes. Maybe because they feel more like configuration to me. @sjmiles, has the team agreed to move over to classes for everything? If so, I'm going to shed a single tear for my homies, the layout attributes :cry:

**Comment by addyosmani** [comment]
Given this change doesn't alter specificity and should enable some more tooling affordance, +1. I don't think the switch to classes is that huge a leap :)

**Comment by ssorallen** [comment]
@robdodson Also, things that look like attributes are actually properties in Polymer (both in 0.5 and 0.8). In 0.5 you had to specify attributes with the `attribute` attribute on the `polymer-element` tag. In 0.8 you have to suffix attributes with a `$` character.

```
```

**Comment by cdata** [comment]
I also liked them. Everyone likes them, really. Even though we sometimes can't express why ;)

Bon voyage, layout attributes :ship:

**Comment by ssorallen** [comment]
@robdodson Also, things that look like attributes are actually properties in Polymer (both in 0.5 and 0.8). In 0.5 you had to specify attributes with the `attribute` attribute on the polymer-element tag. In 0.8 you have to suffix attributes with a $ character.

```
<!-- Which is a property and which is an attribute? -->
<x-foo layout horizontal fly="true"></x-foo>

<!-- ? -->
<x-foo layout horizontal$ fly="true" disabled$></x-foo>

<!-- ?! -->
<x-foo layout$ horizontal fly$ disabled="disabled"></x-foo>
```

**Comment by ssorallen** [comment]
Hmm well if this is not a popular change, then let's not do it.

**Comment by ebidel** [comment]
Maybe it's that people like the brevity?

```
<div layout horizontal>
  <div flex three></div>
  <div flex five></div>
</div>
```

Is easier to read than:

```
<div class="layout horizontal">
  <div class="flex three"></div>
  <div class="flex five"></div>
</div>
```

Another data point, I find myself doing a lot of data binding in 0.5 with the layout attrs:

```
<div layout horizontal vertical?="{{isPhone}}">...</div>
```

vs

```
<div class="layout horizontal {{ {vertical: isPhone} | tokenList}}">
```

or

```
<div class="layout horizontal {{ isPhone ? 'vertical' : '' }}">
```

**Comment by ssorallen** [comment]
I'd favor giving full control of `class` to the binding system:

``` html
<div class="{{ {layout: true, horizontal: true, vertical: isPhone} | tokenList}}"></div>
```

I understand the desire to type less, but it's invalid HTML and goes against what is being taught as the way to target CSS selectors in the community. If the only upside is that you save typing `class=""`, I don't see that as enough value to introduce yet another new thing in what are and will be most dev's introductions to writing Polymer elements.

I seem to be the dissenting opinion here though, so I'm leaning toward abandoning this.

**Comment by cdata** [comment]
I think this should be merged, and while I don't want to speak on behalf of anyone's potentially updated opinions, @morethanreal and @frankiefu both verbally supported this idea as well in previous discussions.

In a world where attributes are the de-facto styling primitive, attributes will inevitably embody style information and element state at the same time. In data-binding scenarios, this can be leveraged in virtuous ways. However, it creates complexity for authors who wish to safely name published properties for their elements without accidentally clashing against names that are likely to be styled against. For example, please consider the following contrived 0.8 Polymer element:

``` javascript
Polymer({
  is: 'x-example',

  published: {
    container: Object,
    grid: Boolean,
    columns: Number
  }
});
```

Are the published properties in the element intended to be styled against? Possibly not. However, if attributes are the primary classification primitive for stylesheets, the element author had better expect it. Those attribute names are taken directly out of three (different) popular CSS grid systems that exist today.

I'm in favor of @ssorallen 's proposal: compute the `className` automatically based on some configuration. It does not exist today, but it seems like a practical addition that will achieve very similar end results to data-binding against style / layout attributes.

I admit that this is not a major concern, but it is one more concern than I have with the "classic" strategy for styling elements.

**Comment by frankiefu** [comment]
Just to me clear, I would rather keep `layout attributes` since we have been using it in 0.5 and people seem to like it.  But I don't have a strong opinion if others in the team have strong feelings and want to change it to `layout classes` instead.

**Comment by cdata** [comment]
With classes and attributes there is a clear distinction - in terms of both obviousness and transparency -  between what defines style and what defines state. This in itself is a virtuous thing, and is worth preserving.

You'll have to forgive the following FUD, but it's a true reflection of my internal worries, so take it as such:

Layout attributes "feel" good, but it's important to remember that this assessment is rooted in subjectivity. The long-term consequences of promoting attributes this way are worth considering. Someday (probably very soon) someone is going to look at layout.html and say, "this is how we should style everything." It's not hard to imagine Classes versus Attributes escalating to the level of a JavaScript ASI bikeshedfest.

**Comment by cdata** [comment]
(don't bother imagining it :smile_cat: you're living it)

**Comment by ssorallen** [comment]
Any comments on a hybrid?

``` html
<div data-layout="horizontal reverse">
  <div data-flex="1 self-end"></div>
  <div data-flex="4"></div>
</div>
```

**Pros:**
- Validates as HTML
- Keeps the "layout feels like config" semantics

**Cons:**
- Values are just like class lists, and so could just be classes

The bottom ~1/3 of the stylesheet (anything unrelated to flexbox) seems like it should still be classes though: `.hidden, .invisible, .fixed-top, etc.`.

**Comment by ssorallen** [comment]
After discussion yesterday with other folks currently building elements, we decided to merge this because of the reasons mentioned in comments. If we spend some time with classes and they prove to be painful in ways that attributes were not, let's discuss and revisit well before we get to a full 0.8 release.

**Pull request merged**
