### PR TITLE
includes shadow-layout.html for Shadow DOM

### PR DESCRIPTION
**Pull request by frankiefu**
includes shadow-layout.html so both Shadow DOM and Shady DOM will work by just importing layout.html.  @sorvell will look at ways to improve this.

### CODE REVIEW

**Comment by ssorallen** [comment]
Do we even need "layout.html" then? The `html /deep/` selectors are more specific than the selectors without it, so all of "layout.html" is duplicate styles that will be ignored.

**Comment by ssorallen** [comment]
Maybe remove "layout.html" and then rename "shadow-layout.html" to "layout.html"?

**Comment by sorvell** [comment]
You need both because browsers without ShadowDOM will eliminate the rules
with /deep/ in them.

**Comment by ssorallen** [comment]
@sorvell Aha, that makes sense. :+1:

**Pull request merged**
